[package]
name = "tuna-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "*"
notify = "4"
anyhow = "1"

tuna = { version = "^0.1", path = "../tuna" }
log = "0.4"
